version: '3'

services:
#Création et configuration de la bdd mysql
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
#'secret' est le mot de passe pour l'utilisateur 'root' sur docker
      MYSQL_ROOT_PASSWORD: secret
#Nom de la base de données sur laquelle seront créées les tables de votre projet symfony
      MYSQL_DATABASE: symfonyTest
      MYSQL_USER: utilisateur
      MYSQL_PASSWORD: mot2Passe
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
#Création et configuration de l'application : l'id de l'image correspond à celui de l'image du fichier Dockerfile    
  app:
    build: .
    ports:
      - '8080:80'
    depends_on:
      - database
#Création de l'image php : l'id de l'image correspond à celui de l'image du fichier Dockerfile       
  php: 
    build: .
#Création et configuration du container phpmyadmin. phpmyadmin s'exécutera sur le port 8000 et se connectera automatiquement
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
#PMA_HOST : sa valeur doit correspondre au nom que vous avez donné à la base mysql définie plus haut. 
#PMA_USER : nom de l'utilisateur avec lequel vous voulez vous connecter (à modifier). Identique à mysql_user défini plus haut
#PMA_PASSWORD (à modifier) : mot de passe correspondant à l'utilisateur avec lequel vous voulez vous connecter. Identique à mysql_password défini plus haut     
    environment:
      - PMA_HOST=database
      - PMA_USER=utilisateur
      - PMA_PASSWORD=mot2Passe
    volumes: 
      - /sessions
      - ~/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

#Crée le container de mailhog. Pour l'envoi, le port sera 1025 sera utilisé. Pour visionner les courriels reçus, il faudra utiliser le port 8025.      
  ui_web:
    image: mailhog/mailhog
    container_name: cont_mailhog
    tty: true
    ports:
      - '1025:1025'
      - '8025:8025'
    restart: on-failure
    environment:
      - MAIL_MAILER=smtp
      - MAIL_HOST=127.0.0.1
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
  
